name: Deploy to AWS EC2 Instance
on:
  push:
    branches: ["prod"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Connect to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/go_bedu:latest

  deployment:
    needs: build
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            docker stop go_bedu || true
            docker rm go_bedu || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/go_bedu:latest
            docker run -p 8080:8080 -d --name go_bedu ${{ secrets.DOCKER_USERNAME }}/go_bedu:latest
