name: Deploy to AWS EC2 Instance
on:
  push:
    branches:
      - prod
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: pull-production-deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd go_bedu-capstone
            git pull origin prod

            # Hentikan proses yang menggunakan port 8080
            pid=$(lsof -ti :8080)
            if [[ -n $pid ]]; then
              echo "Terminating process with PID $pid"
              kill $pid
            else
              echo "No process found running on port 8080"
            fi

            docker-compose down && docker-compose up --build --force-recreate --no-deps -d
