name: Deploy
on:
  push:
    branches:
      - prod
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: pull-production-deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd go_bedu
            git pull origin prod
            docker image prune --force
            docker system prune --all --volumes --force > /dev/null
            docker-compose down && docker-compose up --build --force-recreate --no-deps -d
